"use client";

/**
 * One expense row inside the grouped desktop list (timeline/category views).
 * Shared by both variants — they differ only in the date cell: timeline
 * shows day + weekday under a month header, category shows the full date
 * (no month grouping to lean on).
 */

import { useLocale, useTranslations } from "next-intl";
import { Lock } from "lucide-react";
import type { Invoice, InvoiceType } from "@/types/invoice";
import { formatDate, formatEUR } from "@/lib/utils/formatters";
import { localizeMethodLabel } from "@/lib/payment-methods/localize-method-label";
import {
  REFUND_STATUS_STAMP,
  REFUND_STATUS_I18N,
  refundStatusI18nKey,
} from "@/lib/invoices/refundable-status-display";

export type ExpenseViewVariant = "timeline" | "category";

interface ExpenseRowProps {
  invoice: Invoice;
  variant: ExpenseViewVariant;
  isOpen: boolean;
  onOpen: () => void;
  companyName: string | null;
  typeStampClass: Record<InvoiceType, string>;
}

/** dd from an ISO "YYYY-MM-DD" date string, parsed from the literal parts (no timezone drift). */
function dayOfMonth(isoDate: string): string {
  const match = /^\d{4}-\d{2}-(\d{2})/.exec(isoDate);
  return match ? match[1] : "";
}

/** Localized short weekday (e.g. "MON"), parsed as UTC noon to avoid day-shift. */
function weekdayLabel(isoDate: string, locale: string): string {
  const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(isoDate);
  if (!match) return "";
  const [, yyyy, mm, dd] = match;
  const date = new Date(Date.UTC(Number(yyyy), Number(mm) - 1, Number(dd), 12));
  return new Intl.DateTimeFormat(locale, { weekday: "short", timeZone: "UTC" })
    .format(date)
    .toUpperCase();
}

const ROW_GRID: Record<ExpenseViewVariant, string> = {
  timeline: "64px 1fr 170px 200px 130px",
  category: "92px 1fr 170px 200px 130px",
};

export function ExpenseRow({
  invoice,
  variant,
  isOpen,
  onOpen,
  companyName,
  typeStampClass,
}: ExpenseRowProps) {
  const t = useTranslations("invoices");
  const tBuiltins = useTranslations("paymentMethods.builtins");
  const locale = useLocale();

  const isCategory = variant === "category";
  const methodLabel = invoice.payment_method_label?.trim()
    ? localizeMethodLabel(invoice.payment_method_label, tBuiltins)
    : "";
  const hasRefundArrow = invoice.refundable_status != null && Boolean(companyName);

  return (
    <div
      role="button"
      tabIndex={0}
      aria-expanded={isOpen}
      aria-haspopup="dialog"
      className="expense-row cursor-pointer items-center"
      style={{
        display: "grid",
        gridTemplateColumns: ROW_GRID[variant],
        gap: 12,
        padding: "13px 16px",
        borderBottom: "1px solid var(--paper-2)",
        background: isOpen ? "var(--paper-2)" : undefined,
      }}
      onClick={onOpen}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onOpen();
        }
      }}
    >
      {/* Date */}
      {isCategory ? (
        <div className="num text-[13px] font-semibold" style={{ color: "var(--ink)" }}>
          {formatDate(invoice.issue_date)}
        </div>
      ) : (
        <div className="text-center">
          <div className="num text-[13px] font-semibold leading-none">
            {dayOfMonth(invoice.issue_date)}
          </div>
          <div
            className="mt-0.5 text-[10px] uppercase tracking-wider"
            style={{ color: "var(--muted-2)" }}
          >
            {weekdayLabel(invoice.issue_date, locale)}
          </div>
        </div>
      )}

      {/* Recipient */}
      <div className="min-w-0">
        <div className="flex min-w-0 items-center gap-2">
          <span className="truncate text-[13.5px] font-semibold">{invoice.recipient_name}</span>
          {invoice.is_auto_generated && (
            <span
              className="stamp flex-none"
              title={t("autoGenerated")}
              style={{ fontSize: 9.5, padding: "2px 7px" }}
            >
              <Lock size={9} className="mr-0.5 inline" />
              {t("auto")}
            </span>
          )}
          {invoice.refundable_status != null && (
            <span
              className={`${REFUND_STATUS_STAMP[invoice.refundable_status]} flex-none`}
              style={{ fontSize: 9.5, padding: "2px 7px" }}
            >
              {t(refundStatusI18nKey(invoice) ?? REFUND_STATUS_I18N[invoice.refundable_status])}
            </span>
          )}
        </div>
        <div className="num mt-0.5 truncate text-[11px]" style={{ color: "var(--muted)" }}>
          {invoice.invoice_number}
        </div>
      </div>

      {/* Type stamp */}
      <div className="min-w-0">
        <span className={typeStampClass[invoice.type]}>{t(`types.${invoice.type}`)}</span>
      </div>

      {/* Method stamp */}
      <div className="min-w-0">
        {hasRefundArrow ? (
          <span className="stamp max-w-full truncate">
            {methodLabel ? `${methodLabel} → ${companyName}` : `→ ${companyName}`}
          </span>
        ) : methodLabel ? (
          <span className="stamp max-w-full truncate">{methodLabel}</span>
        ) : (
          <span style={{ color: "var(--muted)" }}>&mdash;</span>
        )}
      </div>

      {/* Amount */}
      <div
        className={`num text-right text-[14px] font-medium${
          invoice.total_amount < 0 ? " text-destructive" : ""
        }`}
      >
        {formatEUR(invoice.total_amount)}
      </div>
    </div>
  );
}
